schema_version = "1.0.0"

id = "autohide_backfaces"
version = "1.0.0"
name = "Auto-Hide Backfaces"
tagline = "Hides backfaces based on camera position, designed to be used with interiors that use flipped normals."
maintainer = "LunaMoca"

type = "add-on"

website = "https://github.com/mocacola02/autohide-backfaces"

tags = ["Modeling", "3D View"]

blender_version_min = "5.0.0"

license = [
  "SPDX:GPL-3.0-or-later",
]